services:
  api:
    build:
      context: .
      dockerfile: relational.e2e.Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    #restart: unless-stopped
    #volumes:
    #  - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped   
    volumes:
      - redis:/data
    #environment:
    #  - ALLOW_EMPTY_PASSWORD=yes
    #  - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'

volumes:
#  postgres:
#    name: boilerplate-db
  redis:
    driver: local
  