name: Build
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test
        working-directory: src/        