name: Build
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          node-version: 20
      
      - name: Run e2e tests
        id: relational
        run: docker compose -f docker-compose.relational.ci.yaml --env-file env-example-relational -p ci-relational up --build --exit-code-from api

      - name: Copy prod.log from container to host
        if: ${{ failure() && steps.relational.conclusion == 'failure' }}
        run: docker cp ci-relational-api-1:/usr/src/app/prod.log .
      


      # 
      #- name: Install dependencies
      #  run: yarn install
      #- name: Run tests
      #  run: yarn run test
      #  working-directory: src/        