name: Release
permissions:
  packages: write
  contents: write
  pull-requests: write
  issues: read
on:
  # Triggered on new GitHub Release
  release:
    types: [published]
  # Triggered on every successful Build action
  workflow_run:
    workflows: ["Build"]
    branches: [ dev ] #[main,master]
    types:
      - completed
  # Manual trigger for rollback to specific release or redeploy latest
  workflow_dispatch:
    inputs:
      version:
        default: latest
        description: Tag you want to release.
        required: true
jobs:
  echo_it:
    runs-on: ubuntu-latest
    name: Starting echo-it job
    steps:
      - name: The echo-it message!
        run: |
          echo "The echoed message."
