name: Unit Tests
'on':
  push:
    branches:
      - feature/*
      - dev
jobs:
  changes_checker:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.check.outputs.run_tests }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for changes in relevant files
        id: check
        run: |
          # Fetch the latest changes from the main branch (or any default branch)
          git fetch origin main

          # Get the list of changed files between the current commit and the main branch
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          echo "Changed files: $CHANGED_FILES"

          # Check if any relevant files (in src or tests) are changed
          if [[ $CHANGED_FILES =~ ^(src/|tests/).* ]]; then
            echo "Tests should be run"
            echo "run_tests=true" >> $GITHUB_ENV
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes, skipping tests"
            echo "run_tests=false" >> $GITHUB_ENV
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi
  run_unit: 
    runs-on: ubuntu-latest
    needs: changes_checker  # This ensures that this job runs only after `changes_checker`
    if: ${{ needs.changes_checker.outputs.run_tests == 'true' }}  # Only run this job if tests should be run
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run Unit Tests
        run: 'yarn run test:unit'
        working-directory: ./
